### PR TITLE
OSOE-464: OSOCE NuGetTest UI testing randomly getting stuck under Windows in Lombiq.UITestingToolbox

### PR DESCRIPTION
**Pull request by Piedone**
OSOE-464

### CODE REVIEW

**Comment by sarahelsaig** [comment]
If I understand correctly this branch won't be merged yet, right?

**Comment by Piedone** [comment]
Not yet, only when I figure out the issue.

**Comment by Piedone** [comment]
Is this deliberately not yet merged?

**Comment by sarahelsaig** [comment]
I was waiting for the tests to finish since I had to merge from `dev`, but I had to leave on an errand.

**Comment by Piedone** [comment]
So you're saying that errands are more important than my PR 🥺.

**Comment by sarahelsaig** [comment]
I'm saying that if there was a "merge on my behalf if all tests pass" switch/bot then none of this would've happened.

**Comment by Piedone** [comment]
There actually is! https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request I'll look into this.

**Comment by 0liver** [comment]
Long live the geek in you! 🤓

**Pull request merged**
