### PR TITLE
OFFI-153: Making JsonSerializerOptions editable

### PR DESCRIPTION
**Pull request by wAsnk**
[OFFI-153](https://lombiq.atlassian.net/browse/OFFI-153)

[OFFI-153]: https://lombiq.atlassian.net/browse/OFFI-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by wAsnk** [comment]
Spell checking error is happing in dev:
https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/11739792772/attempts/2#summary-32868535573

**Comment by sarahelsaig** [comment]
XDoucment and XElement are in the [Xml.txt](https://github.com/Lombiq/GitHub-Actions/blob/4ca5acf0ccf7a943e0d4f8324131074efc54ecb3/.github/actions/spelling/dictionaries/Xml.txt#L6) dictionary which is correctly referenced here so it _should_ work.

But the workflow run [shows this error](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/11798775014/job/32867575694#step:4:2521):
> Error: Failed to retrieve lombiq-lgha:dictionaries/Xml.txt -- HTTP 429 for https://raw.githubusercontent.com/Lombiq/GitHub-Actions/dev/.github/actions/spelling/dictionaries/Xml.txt (extra-dictionary-not-found)

Please open a GHA issue and disable the spelling workflow in the meantime.

**Comment by wAsnk** [comment]
> XDoucment and XElement are in the [Xml.txt](https://github.com/Lombiq/GitHub-Actions/blob/4ca5acf0ccf7a943e0d4f8324131074efc54ecb3/.github/actions/spelling/dictionaries/Xml.txt#L6) dictionary which is correctly referenced here so it _should_ work.
> 
> But the workflow run [shows this error](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/11798775014/job/32867575694#step:4:2521):
> 
> > Error: Failed to retrieve lombiq-lgha:dictionaries/Xml.txt -- HTTP 429 for https://raw.githubusercontent.com/Lombiq/GitHub-Actions/dev/.github/actions/spelling/dictionaries/Xml.txt (extra-dictionary-not-found)
> 
> Please open a GHA issue and disable the spelling workflow in the meantime.

My favorite kind of problem is the one that fixes itself.

**Comment by sarahelsaig** [comment]
> My favorite kind of problem is the one that fixes itself.

image

**Pull request merged**
