### PR TITLE
OSOE-64: Missing UI Testing Toolbox PR

### PR DESCRIPTION
**Pull request by sarahelsaig**
OSOE-64

### CODE REVIEW

**Comment by Piedone** [comment]
Didn't you want to not enable Lombiq.Privacy.ConsentBanner from the test recipe?

**Comment by sarahelsaig** [comment]
> Didn't you want to not enable Lombiq.Privacy.ConsentBanner from the test recipe?

That was already done in the previous PR here: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/46/files#diff-9374b8cb4188c7529617966bdca88fa57f554e6267be8c3f0a229649f45efdd8L35

**Comment by sarahelsaig** [comment]
Initially I have only disabled "Lombiq.Privacy.ConsentBanner" but then `BasicOrchardFeaturesShouldWork` failed because the messages in admin (like content successfully published) didn't show up. Is that normal?

I have commented out the other two("Lombiq.Privacy.FormConsent" and "Lombiq.Privacy.RegistrationConsent") from the recipe  and then the test successfully passes in local.

**Comment by Piedone** [comment]
No, the admin notifications shouldn't be related to the Privacy module at all.

**Comment by sarahelsaig** [comment]
Looks like the webroot bug was unrelated, because I'm getting this damn error again.
```
2022. 03. 25. 15:45:48 UTC | Severe | network | https://dc.services.visualstudio.com/v2/track - Failed to load resource: the server responded with a status of 400 ()
```

**Review by barthamark — APPROVED** [review]

**Pull request merged**
