### PR TITLE
Monkey testing

### PR DESCRIPTION
**Pull request by YevgeniyShunevych**
Corresponding UI Testing Toolbox PR: https://github.com/Lombiq/UI-Testing-Toolbox/pull/109

**Before merge:** Remove debug code!

### CODE REVIEW

**Review by Piedone — CHANGES_REQUESTED** [review]
There's an NRE in UI tests now.

**Comment by YevgeniyShunevych** [comment]
Here is the original error source that I'm getting locally too:

image

NRE happens in that catch block lower because the `UITestContext.Driver` property is `null`. But original cause of the error is in SQL Server.

**Comment by Piedone** [comment]
Add null checks in `GetPageTitleAndAddress()` then, please.

**Comment by YevgeniyShunevych** [comment]
Added. Here is the commit: https://github.com/Lombiq/UI-Testing-Toolbox/commit/29e68aea1fc9ccc7ffa63bfea1f313b19eeb6f79.

**Review by Piedone — APPROVED** [review]

**Review by Piedone — APPROVED** [review]

**Review by Piedone — APPROVED** [review]

**Review by Piedone — APPROVED** [review]

**Review by Piedone — APPROVED** [review]

**Pull request merged**
