### PR TITLE
OSOE-342: Workflows activity sample

### PR DESCRIPTION
**Pull request by adelgeiszt**
OSOE-342

### CODE REVIEW

**Review by domonkosgabor — APPROVED** [review]

**Review by Piedone — APPROVED** [review]

**Review by Piedone — CHANGES_REQUESTED** [review]
Note https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/226#issuecomment-1285462565

**Comment by Piedone** [comment]
Merge from the `dev` branch to your issue branch to make sure that all submodules are on the latest, fixed-spelling state.

**Comment by adelgeiszt** [comment]
I messed up the branch with rebase. I tried to revert it but did not solve the issue. It looks like I cannot fix it without force push and it would be easier to create a new branch and PR with the required changes. Is it okay or what would you suggest?

**Comment by Piedone** [comment]
You can delete your branch and restart it from the current `dev`.

image

image

This will make your changes to this repo vanish, but you didn't do anything else apart from updating the submodule, so that's not an issue.

**Pull request closed without merging**
