### PR TITLE
OSOE-84: ⭐ Migrate OSOCE to Node.js Extensions

### PR DESCRIPTION
**Pull request by 0liver**
OSOE-84

Opened this PR to monitor the correctness of the task branch.

### CODE REVIEW

**Comment by sarahelsaig** [comment]
> Opened this PR to monitor the correctness of the task branch.

So this doesn't need a review, right? Should it be converted into a draft?

**Comment by 0liver** [comment]
> So this doesn't need a review, right?

Correct. All changes here should have been reviewed, or have been merged from `dev`. The PR exists so we catch build errors here, not in dependent issue branches.

> Should it be converted into a draft?

Good point. Done.

**Comment by 0liver** [comment]
Will reopen once OSOE-84 is merged.

**Comment by 0liver** [comment]
It's about time.

**Comment by Piedone** [comment]
On the next commit, UI testing will break if you don't merge from `dev` beforehand.

**Pull request closed without merging**
