### PR TITLE
OSOE-172: ⭐ Check if all packages are consolidated in a solution during build

### PR DESCRIPTION
**Pull request by Piedone**
OSOE-172

- [Example of the build failing due to consolidation being required](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/8098746793?check_suite_focus=true).
- [Example of the build passing when the solution is consolidated](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/8098818525?check_suite_focus=true)

### CODE REVIEW

**Review by dministro — CHANGES_REQUESTED** [review]
Please create PR for submodule changes where required or revert.

**Comment by Piedone** [comment]
Good catch, but apart from GHA, they were trivial changes, and I pushed them to `dev` (perhaps shouldn't have in hindsight).

**Comment by dministro** [comment]
Please never push to `dev` directly, use issue branches instead.
[Issue branches and pull requests](https://lombiq.atlassian.net/wiki/spaces/DEV/pages/1343509/Daily+development+tips+and+to-dos#Issue-branches-and-pull-requests)

**Review by dministro — APPROVED** [review]

**Comment by Piedone** [comment]
You're right :). Will do that next time.

**Pull request merged**
