### PR TITLE
Licence -> License

### LINKED ISSUE #52: Rename Licence.md files to License.md (OSOE-80)
We used British English but since we use American English for everything else, let's rename them. Note that submodule repos with more than one project and published to NuGet have not just a file in the root but in each published project's folder too.

Apart from the file renames, the references for NuGet build in the csprojs need to be adjusted too.

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #52

### CODE REVIEW

**Comment by hishamco** [comment]
I think the same change should be done in the sub-modules, it's done in this repo or for each repo?

**Comment by Piedone** [comment]
Thank you. And yes, it need to be done for each repo, in their repos, see the issue.

**Comment by hishamco** [comment]
I will do the same thing for every repo, you could merge this then

**Comment by Piedone** [comment]
https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/90 supersedes this. Thank you for doing this, but this needs to be done in all submodules too.

**Pull request closed without merging**
