### PR TITLE
OSOE-559: Fix intermittent errors in NE with "pnpm link", update ClosedXML

### PR DESCRIPTION
**Pull request by 0liver**
[OSOE-559](https://lombiq.atlassian.net/browse/OSOE-559)

[OSOE-559]: https://lombiq.atlassian.net/browse/OSOE-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dministro — APPROVED** [review]

**Review by dministro — APPROVED** [review]

**Review by dministro — APPROVED** [review]

**Comment by dministro** [comment]
Strange error on Windows runner, on Linux the build completes without any problem.

https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4388557195/jobs/7685183926#step:6:114

image

@0liver can you take a look?

**Comment by 0liver** [comment]
Please re-run the failed run. This is an intermittent error that I'll have to investigate on its own. I've seen similar errors, but with different commands - here it's `postcss`; I've seen it with `sass` before.

I'll create an issue for that.

**Comment by dministro** [comment]
Ok, I agree. I restarted the build already.

**Comment by 0liver** [comment]
New issue: https://github.com/Lombiq/NodeJs-Extensions/issues/39.

**Pull request merged**
