### PR TITLE
Ability to access table in collection

### PR DESCRIPTION
**Pull request by szilardcsere89**
[PR](https://github.com/Lombiq/Helpful-Libraries/pull/139)
[Issue](https://github.com/Lombiq/Helpful-Libraries/issues/137)

### CODE REVIEW

**Comment by 0liver** [comment]
Please fix [the following problem](https://ci.lombiq.com/buildConfiguration/OrchardExtensions_OSOCE_Developer_PullAndBuild/1033736?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true):

> - Lombiq.TrainingDemo.Tests -> C:\BuildAgent\work\OSOCE\src\Modules\Lombiq.TrainingDemo\Tests\Lombiq.TrainingDemo.Tests\bin\Release\net6.0\Lombiq.TrainingDemo.Tests.dll
> - C:\BuildAgent\work\OSOCE\src\Modules\Lombiq.DataTables\Lombiq.DataTables\Services\DeletedContentItemDataTableDataProvider.cs(89,44): error CS0854: An expression tree may not contain a call or invocation that uses optional arguments

**Comment by Piedone** [comment]
And keep checking the build results here under the PR after a push, and fix issues until it's green.

**Comment by szilardcsere89** [comment]
So I have to do the followings:
1. Fork Lombiq.DataTables
2. Fix the bug: 
image
3. Commit
4. Pull into OSECE (via submodules)
5. Push

Is there something missing?

(Sorry, never worked with git submodules. The solution is not building in VS for me)

**Comment by Piedone** [comment]
Yes, this is it, just please also open a PR for DataTables (exactly how you've done for Helpful Libraries).

**Comment by szilardcsere89** [comment]
Ok, thank you! I'll do it soon.

**Comment by Piedone** [comment]
Sorry, I wasn't expecting us having to provide a parameter in all cases like it happens here: https://github.com/Lombiq/Orchard-Data-Tables/pull/101/files#diff-345f66ee89bad0443cea7598e83860985f4de372be5937501b535d534394d8c3L87 For that, we do need both the original `GetTable()` and the overload with the parameter. Then, the DataTables modification shouldn't be needed.

**Comment by szilardcsere89** [comment]
It's okay. I'll create an overload for the method with a required parameter. Should I do this in the case of `LinqTableQueryAsync` method too?
Is it okay if I just cancel the [PR](https://github.com/Lombiq/Orchard-Data-Tables/pull/101)?

**Comment by Piedone** [comment]
> I'll create an overload for the method with a required parameter. Should I do this in the case of LinqTableQueryAsync method too?

Yes, please.

And yes, you can just close the PR if it's not needed in the end.

**Comment by Piedone** [comment]
Would you like to get back to this?

**Comment by szilardcsere89** [comment]
I'd like to, asap have some time.

**Comment by Piedone** [comment]
Great, thanks!

**Comment by Piedone** [comment]
I'm taking over this under https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/148 so we can integrate it. Thanks for your contribution, the majority of it will remain under your name, of course.

**Comment by szilardcsere89** [comment]
Ok, sorry. Thank you!

**Pull request closed without merging**
