### PR TITLE
OSOE-675: Set StopOnFail option to true un xunit.runner.json for Lombiq.OSOCE.Tests.UI

### PR DESCRIPTION
**Pull request by tteguayco**
[OSOCE-675](https://lombiq.atlassian.net/browse/OSOCE-675)

This configuration file is ignored when running the tests directly from VisualStudio.

It takes the configuration file into consideration when running the tests via dotnet test.

A related issue was opened: https://github.com/xunit/visualstudio.xunit/issues/392

### CODE REVIEW

**Comment by DemeSzabolcs** [comment]
@tteguayco I pushed a little change, otherwise good. BTW the previous branch was okay, we are using `OSOE` naming for the branches, not `OSOCE` but no problem, it can stay now.

**Comment by tteguayco** [comment]
Thank you @DemeSzabolcs!

**Comment by DemeSzabolcs** [comment]
@tteguayco Sorry, there are two more problems, could you please open another PR for fixing them?

1. You will also need to add config in `Lombiq.Tests.UI.Samples`
2. And you will need to add a note about it under https://github.com/Lombiq/UI-Testing-Toolbox/blob/dev/Lombiq.Tests.UI/Docs/Configuration.md#external-configuration.

**Comment by tteguayco** [comment]
@DemeSzabolcs Sure, no problem. Two questions though:

1. Would it be the same config file?
2. What should the note include? Usage about `stopOnFail`?

**Comment by DemeSzabolcs** [comment]
Thank you!

1. Yes.
2. Yes, see the end of this original comment: https://github.com/Lombiq/UI-Testing-Toolbox/issues/309#issuecomment-1794842791

**Comment by tteguayco** [comment]
Hey @DemeSzabolcs 

Should the note really be included at the end of section https://github.com/Lombiq/UI-Testing-Toolbox/blob/dev/Lombiq.Tests.UI/Docs/Configuration.md#external-configuration? It looks like the snippet there being:
```
{
  "Lombiq_Tests_UI": {
    "AgentIndex": 3,
    "TimeoutConfiguration": {
      "RetryTimeoutSeconds": 5,
      "RetryIntervalMillisecondSeconds": 300,
      "PageLoadTimeoutSeconds": 120
    },
    "OrchardCoreUITestExecutorConfiguration": {
      "MaxRetryCount": 0,
      "RetryIntervalSeconds": 0,
      "MaxParallelTests": 0
    },
    "BrowserConfiguration": {
      "Headless": true
    }
  }
}
```

is not a `xunit.runner.json` like the one that was modified as part of this work.

**Comment by DemeSzabolcs** [comment]
@tteguayco Hello. No that is not related, I think the best would be at the end of this part that mentions `xunit.runner.json`: 
image

**Comment by tteguayco** [comment]
@DemeSzabolcs Awesome. I just created this PR (and the corresponding one for the OSOCE top-level solution): https://github.com/Lombiq/UI-Testing-Toolbox/pull/325

**Pull request merged**
