### PR TITLE
OSOE-517: Update submodule ref LGHA for issue/OSOE-517 merge queue support

### PR DESCRIPTION
**Pull request by davidpuplava**
[OSOE-517](https://lombiq.atlassian.net/browse/OSOE-517)

[OSOE-517]: https://lombiq.atlassian.net/browse/OSOE-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

## Summary by CodeRabbit

- **Chores**
	- Updated a subproject to the latest commit for improved stability and performance.

### CODE REVIEW

**Comment by DemeSzabolcs** [comment]
The PR is failing due to PowerShell issues: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7074667646/job/19255965083?pr=635#step:3:14

**Comment by davidpuplava** [comment]
>The PR is failing due to PowerShell issues

Thank you - I corrected and pushed

**Review by DemeSzabolcs — APPROVED** [review]

**Comment by Piedone** [comment]
Shouldn't this be merged?

**Comment by DemeSzabolcs** [comment]
Yes, sorry I don't know how I skipped this.

**Pull request merged**
