### PR TITLE
OCC-245: Update OC

### PR DESCRIPTION
**Pull request by sarahelsaig**
[OCC-245](https://lombiq.atlassian.net/browse/OCC-245)

[OCC-245]: https://lombiq.atlassian.net/browse/OCC-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sarahelsaig** [comment]
This is all done, I'm only waiting for the Windows visual verification pic to generate on the server since I can't do it locally.

**Review by Piedone — CHANGES_REQUESTED** [review]
Merge `dev` to `task/system-text-json-migration` please, because this now contains a lot of unrelated diff. Or otherwise, ideally keep `task/system-text-json-migration` up-to-date with `dev`, but more importantly, keep the issue branch up-to-date with ``task/system-text-json-migration`.

**Review by Piedone — APPROVED** [review]
The NuGet updates and reactivation of the NuGetTest builds are then remaining steps once we have the submodules finalized.

**Review by Piedone — APPROVED** [review]

**Comment by Piedone** [comment]
Now please update NuGetTest.

**Comment by sarahelsaig** [comment]
> Now please update NuGetTest.

Why is that necessary? Do we anticipate anything different in NuGet that would justify the effort of publishing all remaining Lombiq projects to Cloudsmith as well?

**Comment by Piedone** [comment]
Not to Cloudsmith, to NuGet, as alphas as usual. Because now the NuGet build is disabled and the NuGetTest app is not updated.

But if you think that upgrading that solution to 2.0 won't be a big deal once all the packages are published, then we don't need to do it now.

**Review by Piedone — APPROVED** [review]

**Review by Piedone — APPROVED** [review]

**Pull request merged**
