### PR TITLE
OSOE-620: ⭐ Update all packages to latest

### LINKED ISSUE #460: Update all packages to latest (OSOE-620)
...in all submodules too, once https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/378 is done.

- [x] When a UI test fails, currently an HTML snapshot is saved into the FailureDumps folder. This should rather be an MHTML with compatible Chromium browsers. This worked before but now it appears to revert back to HTML, perhaps due to some Chrome change. If this happens with the latest Atata too, then report it [here](https://github.com/atata-framework/atata/issues).
- [x] [`Microsoft.AspNetCore.Http`](https://www.nuget.org/packages/Microsoft.AspNetCore.Http/) is now deprecated. Remove it and use a substitute if necessary.
- [x] Don't forget about the NuGetTest solution.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-620)

### PR DESCRIPTION
**Pull request by sarahelsaig**
[OSOE-620](https://lombiq.atlassian.net/browse/OSOE-620)
Fixes #460

[OSOE-620]: https://lombiq.atlassian.net/browse/OSOE-620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Psichorex** [comment]
@DAud-IcI Checks are still failing after merging submodule PRs. I can't tell atm if I am the one who is missing a step or something is still wrong with the PR itself.

**Comment by sarahelsaig** [comment]
Exactly, so why the heck did Lombiq Bot still put it to "Done"?!

**Comment by Psichorex** [comment]
> Exactly, so why the heck did Lombiq Bot still put it to "Done"?!

Because your previous build was actually successful and it was failing after I merged LOL

**Comment by DAud-IcI** [comment]
I mean in this PR. Also the [test it complains about](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/5374413490/attempts/1#r6a785dca0s2) passes for me locally in Window.

**Comment by sarahelsaig** [comment]
Finally managed to coax out some actual error report

> response.IsSuccessStatusCode     should be True     but was False  Additional Info:     Tenant creation failed with status code Unauthorized.

Still can't reproduce it locally though.

**Comment by Piedone** [comment]
Build is failing.

**Comment by sarahelsaig** [comment]
I know, the bot is just being whack again and pushing the issue to Done even though the build has clearly failed.

btw the problem is already in the NuGet package (v3.0.1-alpha.0.osoe-616), because at this point the "Build and Test Windows - NuGetTest solution / Build and Test (windows-2022)" fails.

**Comment by Piedone** [comment]
It did that because a build passed after you added the label, which wasn't the most recent build that failed. I created an issue to make this more sophisticated: https://github.com/Lombiq/GitHub-Actions/issues/241

**Comment by sarahelsaig** [comment]
It says "Unauthorized" on Windows. I doubt the port is blocked, because that's the same port we use for the web driver. I'm really confused.

```
Refit.ApiException: Response status code does not indicate success: 401 (Unauthorized).

Additional Info:
    Tenant creation failed with status code Unauthorized. Content: 
Request: Method: POST, RequestUri: 'https://localhost:9000/api/tenants/create', Version: 1.1, Content: System.Net.Http.PushStreamContent, Headers:
{
  Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZDQkMtSFM1MTIiLCJraWQiOiIwRTI2NzRBMThENUEzRUQzMTI1NDdEN0ZFRTNFMjNBQzVEOTY0MDBBIiwidHlwIjoiYXQrand0IiwiY3R5IjoiSldUIn0.nER4hcEtT5p9khn_S_Tq7_QhwuCZzOscZL9hJZQPmwRINiUx2mZbCdoF9iT_r45JDC1ezYjIXPek60WYKcxHAzh-KjHBRwH5jp0yhzoyA-DFYFTyUaKBiCsbdYIi9YnQrc_x3aJ7O8zJWJHms6NGBy1As5BeyAbir9M62tGDfABPn7hG5sYrdMc2oRe0lMn0_Et1SKf-_cYUjdzNuVaG_Kl2V6oIIr6331nHczMeNCazVaW1hULW4r75JLkpVOLyAV2mZTa9pKu_io7BZuD9KTtwGvIIrPO0oQTz5XiG96FZSSvFMuCab4rXEJYTDAfRNTts6aPfclll3yOv5ueeLA.6f2a89mhf8Fmq7mQuG6o5g.iOZqQB7534hXLAValtLIh2Ev5_jWx_c3cUGUQTyjOOjuNiDERmE1JUc3Md6MELg2LCVVQd7QlWr4F6Hm2y1oi9JzrEIINOz47dKuZ5pEKmUBk_yvwBDCdpdNgOyYIh6sfLsQPrr2WaaWpFkKyThWcQvk7tYqFMe2hPhKqjK9RAU0THZLAv62tt-3c3LydwH5KksJ0x5Vy3hYBm4COlk53qIgaCtKP7jUQBjl4bEWUileQktpnaF7ZejhTdZbDdnKWDkuIOzpn3JpIjs00V3lW-d6Y1m9lrjnsco-N5ADYY9JHHq-ThyUrOddyWAB5oJhK7YtKVIHfu5YIsddPsE-KMjJqQuIG-cDVQtrE2h_udQmredPpJkl28KUPUyF2Onx01ld73amgQepeUNOsvX3sqMhgiUGL_rj6Xj-Gl5qvmp4VVx4r0ckheZNVUciNjns83d15rySUaOwwk1PT8fX4oQwrhPYx3XT0c9nJOv2C6Ipd-DWcwKCH2Coi0Xb45Frt-9MrNcLdXSZqsrYj4RQYhQIfCzvLTVUPi58rHDXV7O61ozQGoEBhun7KL_c8Luzf_M0yBKdQaGlJknTPDGK8Pb0v4P5vpc9fbhFArUmkdnUE303MhDccYxDFor7b1007uEXBtHx0I8bWkW0pdfMcn2aEEHjltYefOARbnBBRfjVn_Zlb3ZzDa68e1Y_VbM4-8Yw5RI-r6HEmM3Nz2UpgR3HWfAtaW6RQGVVPuvLO0STUUhlJOGaqbvsQsgxqDNNCxOyovZ7bQCohUNP7TpUi1faSA1Y-6SrQBkcsOvRtct9dcQaAnk_ffspdLPjUFPP2FUNqFg-JgcWggCeLHnB4IquxYQpknkimQzlIx9KKNHBWZsSU3-YT52p0yGwVOym1QuRCuic8TW8VUTGma6_4ZSb9OAoRSE9KBhvUBmtNxdG9u8XP6EikI1BwgOSmztDpf0p2vdIk6MBL29Zo0petYnuo3fVwOG6R8mBAo-dt8ybhX77kc8dQu5e2w9ZO1W1Qodn1JzbrPYn0IhSqrQSDdKmpagt8PPxoCBIibpkPc3XHF_C1R9TB1wTkgAhiKBZNoMF67WKsKu-v30iteHbmPhH87tuYtBQ2WYUlMZ6DddNzm6IwZADR88NgsiOc-YRrWvM1-2aClbthPTJ3t8Ftu5UU5yxYCoq5Dto1q2g5ygAQRLSWFtIw6Nf6K_-dLpr0zqT9QqHdEjrbDqqia94Iv3MXD4oY22BTwE2u_exDMehgnCFFWK2T3DzIRQFTauA1_a1y2Mo2reyH5fdyG6W32A_KYfFizx73xA5jT5ay3NN14axx0O-gQ2Jmm4-JPwFB8QsG89x3DZH3t8E_FYMudZt4GLikpP6eHe8WuMXAftVxMfksEraxDP5vvMQ7rkrSKmBZoThK63dfV2yD-MzXYvfkle5QEPOgHMeYdSFcZnV5UNtC9qSOcaWtfn0VqXpMgSDpDb7XnyrTeFj-fb_8xAn4YG8COjeuZ4LJ4pfd7A7VXOyfDaolHWR-BCEKkWJYVK4yaWRaB95ps2WWqWcOQYC2qjO3E426bvwmQRBGWwckYv_DJkRyUbYZxh1uLBx8SERHa82eUjLiE_t2gZ9gFRpWy3SitLL_Z0cLM-tvvwF_L2AOaNJjZtdi8x8TtP9rZkVsk47EDe86qvSiBaISGhSCTiA6RN-7EADbFMod8yJyTSRE6UBFi4YcsWdQW4FnYdlZFIaJC2t-QskA_iAJoArfo26mkFVJ2VF-NIZrFF3eURL3Kl1yqW6JSrfNqrpX4nbz8kIpYIZhT0_s11XcyOCGo3OAt-ab2LARJg91SOexqqUolMS128_UiZCH6hNloclLpW8t8ADzOooCB0Swk7X0C25_PsmRmyyWqx0fjIXaDVZ18EUvkZO5Qn-o9QoYnRhriCAP5wydMvXnPe2hxemEoMQQo2je9uvghP2xqLeCp_iLp5gExzRrqqV4Ekpn4o9qIPyq-22psIaw7HKd5ncvkveKsxvIKtLj1R0UmWwaLXbNp5L7gike9XySvCZPV8Aqbq2cDoIFloq21c9iqY9etaZ54uEN_BSWwY5lvlD8q0dsR-S3xYSkwm6VPHke1SYy19myXHXsEif_LTpxe80BfeGbwwprL5iO1T-CvQGnhM1TdQOexJBTWtNbLog6-C2PaQ24KHburGKZL1ofTLu0GGFNHuLJG9X305ZxygW7kFVDY498CYpqFjBIC0BnsO4v8NgWo2keqTRUkRxHdZeMSoSDhUuhXKvwksRdRBVSYkFInH31FgHauHepayC77iiVSiZg8FdYVy2AK5ACA-0qoqQxt0sMwiD5BylM5HfSB3lgVwMM74BameornVycWJ6Gam7p9rOZ7ocokwnnGzbrZ7ljx9fW01ehTR9WvKz_HZTE-8dg8kIectlBqvRIvezxq5b59_Lff8F9KFkoQ.iTXgml4_nZEzBFFR545utfjwIk8E9dRGS_XBFE8Z9B8
  Transfer-Encoding: chunked
  Content-Type: application/json; charset=utf-8
}
Driver URL: https://localhost:9000/Lombiq.Tests.UI.Shortcuts/Account/SignInDirectly?userName=admin
```

**Comment by Piedone** [comment]
This looks like more of an auth issue with the API, i.e. something with OpenID in OC. Perhaps the recipe that sets up access is not always executing correctly? Check out the DB in the failure dump.

**Comment by sarahelsaig** [comment]
> This looks like more of an auth issue with the API, i.e. something with OpenID in OC. Perhaps the recipe that sets up access is not always executing correctly? Check out the DB in the failure dump.

I've added logging to check and the recipe is definitely executing. Also I'm certain if that was the problem it wouldn't work in local Windows either. I took a look at the `OpenId_Document` table in the DB but I'm not sure what I'm supposed to see. It has two records:
```json
{
    "ApplicationId": "d9b5e6f030734cfe967ebd1fe6945a9c",
    "ClientId": "UITest",
    "ClientSecret": "AQAAAAEAACcQAAAAEBHn9HTZq+/zK2ku4hSnZqTXWDYFB8pdP6JgitPkgmsnrrDfxd7tGpt6x3VrSMnMug==",
    "DisplayName": "UITest",
    "DisplayNames": {},
    "Id": 1,
    "Permissions": [
        "gt:client_credentials",
        "ept:token"
    ],
    "PostLogoutRedirectUris": [],
    "RedirectUris": [],
    "Requirements": [],
    "Roles": [
        "Administrator"
    ],
    "Type": "Confidential"
}

{
    "ApplicationId": "d9b5e6f030734cfe967ebd1fe6945a9c",
    "CreationDate": "2023-06-27T17:25:45Z",
    "ExpirationDate": "2023-06-27T18:25:45Z",
    "Id": 2,
    "Status": "valid",
    "Subject": "UITest",
    "TokenId": "1f481af7598d4f9b9d530981748cde20",
    "Type": "access_token"
}
```

The IDs change from attempt to attempt, but otherwise it's the same.

**Comment by Piedone** [comment]
Does the API work locally for you with the app snapshot from the failure dump?

Yeah, the test does pass for me locally too (under Windows). However, I do that from within VS. Perhaps something is different when you run tests with the Release binaries of the app (but Debug binaries of the UI testing project), like GHA does?

**Comment by sarahelsaig** [comment]
> Does the API work locally for you with the app snapshot from the failure dump? 

I guess? I've copied it into the app and then was able to create a new tenant with the tester app.
Also I ran the `Invoke-SolutionTests.ps1` with the same arguments seen in the GH log (but with the additional `--filter "FullyQualifiedName~BehaviorOrchardCoreApiClientTests"` switch for `dotnet test` to save time) and that passed as well.

> Perhaps something is different when you run tests with the Release binaries of the app (but Debug binaries of the UI testing project), like GHA does?

Is that still the case? I thought this quirk was only applicable before OSOE-46.

**Comment by Piedone** [comment]
It is. the app is built with Release ([see](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/build-and-test-orchard-core.yml#L209)), while test projects are (by default) built with Debug ([see](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/test-dotnet/action.yml#L37)).

**Comment by sarahelsaig** [comment]
Okay, but looking through the `test-dotnet` action and the `Invoke-SolutionTests.ps1` script, I don't see signs that the release binary from `build-and-test-orchard-core` is actually used at all. I brought up OSOE-46, because before that change indeed the UI test used the release build as a separate executable, but as far as I understand the whole point of that change was that now the OC webapp and the UI test are in a single assembly. Maybe I'm just confused, but this seems off the mark.

**Comment by Piedone** [comment]
It's indeed a single executable, with the test project at the root. However, the web app project that it references, and the modules and themes, are still built in Release.

**Comment by sarahelsaig** [comment]
After sweating buckets of blood and giving birth to several cacti, I have narrowed the problem down to a platform-specific decryption error.

> An error occurred while validating the token.
> Microsoft.IdentityModel.Tokens.SecurityTokenKeyWrapException: IDX10618: Key unwrap failed using decryption Keys: 'Microsoft.IdentityModel.Tokens.X509SecurityKey, KeyId: '25D4C4EE14D7475F51503A0DF2E7BFABEB897713', InternalId: 'JdTE7hTXR19RUDoN8ue_q-uJdxM'.
>
>Microsoft.IdentityModel.Tokens.SecurityTokenKeyWrapException: IDX10659: UnwrapKey failed, exception from cryptographic operation: 'Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The parameter is incorrect.
   at System.Security.Cryptography.RSACng.EncryptOrDecrypt(SafeNCryptKeyHandle key, ReadOnlySpan`1 input, AsymmetricPaddingMode paddingMode, Void* paddingInfo, Boolean encrypt)

(note the exception type, `WindowsCryptographicException`)

I've also tried to look around in the related OC and OpenIddict code and tried to log as much tracing info as much as it's feasible without the ability to reproduce the problem on my own machine. Since it's cryptography-related, I wonder if some OS level configuration is incorrectly set up in the GH Windows runner
In the end, my workaround was to disable token encryption in the `OpenIdServerSettings`. I know this is not safe in normal operation, but it's fine for UI testing. If anyone actually experiences this problem outside of GH, they can file an OC issue about it.

**Comment by 0liver** [comment]
`*Sarcarsm*`: You could donate that blood and save some poor souls' lives! At least this much good would come out of your enormous effort!

**Comment by Piedone** [comment]
Oh wow, congrats! Just please make sure to add a comment about this to the recipe (including, if necessary, a link to this comment).

**Comment by sarahelsaig** [comment]
> `*Sarcarsm*`: You could donate that blood and save some poor souls' lives! At least this much good would come out of your enormous effort!

And what shall I do with the these? 🌵🌵🌵

**Comment by Piedone** [comment]
I'm just glad no hedgehogs joined the cacti.

**Comment by 0liver** [comment]
@DAud-IcI Let me tell you a joke.

A German, a Pole, and a Russian are caught by the devil. In a moment of weakness he says to them: "If you do what I tell you, I will let you go!" They all agree. "Go and bring back a plant!", the devil says.

The three run of looking for a plant.

The German returns first, with a rose. "Eat it, and I will let you go", says the devil. The German chokes on the rose, the thorns scratch his throat, but finally he swallows the whole of it, and the devil sends him off.

The Pole returns second, with a daisy. "Eat it, and I will let you go", says the devil again. The Pole starts chewing the daisy, and has already swallowed half of it when he suddenly starts laughing to tears. The devil gets annoyed: "Why are you laughing?" The Pole can hardly catch his breath, but finally says: "The Russian is coming back, and he's carrying a cactus!"

**Review by Psichorex — APPROVED** [review]

**Pull request merged**
