### PR TITLE
NEST-295: Orchard Core API client

### PR DESCRIPTION
**Pull request by MZole**
[NEST-295](https://lombiq.atlassian.net/browse/NEST-295)

- https://github.com/Lombiq/Orchard-Core-API-Client/pull/1
- https://github.com/Lombiq/Orchard-Core-API-Client/pull/2
- https://github.com/Lombiq/Orchard-Core-API-Client/pull/3

### CODE REVIEW

**Review by wAsnk — APPROVED** [review]

**Review by wAsnk — CHANGES_REQUESTED** [review]
Ups, actually you have a test that's failing.

**Review by Piedone — CHANGES_REQUESTED** [review]
Keep to https://lombiq.atlassian.net/wiki/spaces/OSOE/overview.

**Review by Piedone — CHANGES_REQUESTED** [review]
As asked, keep to https://lombiq.atlassian.net/wiki/spaces/OSOE/overview.

**Comment by MZole** [comment]
What am I missing exactly? The only two things I have found are the NuGet publish and shield, but these should be done after the PR merged as I understand.

**Comment by MZole** [comment]
> As asked, keep to https://lombiq.atlassian.net/wiki/spaces/OSOE/overview.

What am I missing exactly? The only two things I have found are the NuGet publish and shield, but these should be done after the PR merged as I understand.

**Comment by Piedone** [comment]
Go through everything [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions#contributing-and-support), which is one of the things linked from the wiki.

**Review by Piedone — APPROVED** [review]

**Pull request merged**
